name: .NET FRAMEWORK Build, Test, Package, and Report Coverage

on: 
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
 
jobs: 
  buildall:
    name: Build and Test .NET FRAMEWORK
    runs-on: windows-latest

    strategy:
      matrix: 
        framework-version:
          - '4.7.x'
          - '4.8.x'

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.framework-version }}
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: ${{ matrix.framework-version }}

      - name: Display .NET version 
        run: dotnet --version 

      - name: Install gloal dependencies 
        run: dotnet tool restore 

      - name: Restore Solution 
        run: dotnet restore 

      - name: Build Solution
        run: dotnet build ./nugetMultiTarget.sln /warnaserror /c Release

      - name: Run Tests 
        run: dotnet test ./nugetMultiTarget.sln /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

      - name: Upload coverage report for .NET 
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./TestResults/coverage/lcov.info

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --output ./artifacts

      - name: Upload NuGet package
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: ./artifacts/*.nupkg



